export { default as contentReducer } from './reducer'
export type { CV } from './model'
export { default as cvReducer } from './reducer'
export { useCV } from './hooks'
export { useFullName } from './name'
export { usePosition } from './position'
export { useAvatar } from './avatar'
export { useAboutMe } from './aboutMe'
export { useExperiences, MAX_EXPERIENCES_SIZE } from './experiences'
export { useEducations, MAX_EDUCATIONS_SIZE } from './educations'
export { useContacts, MAX_CONTACTS_SIZE } from './contacts'
export { useTechnologies } from './technologies'
export { useLanguages, MAX_LANGUAGES_SIZE } from './languages'
