export const MAX_CV_VERSIONS = 5

export const MAX_FULL_NAME_LENGTH = 50
export const MAX_POSITION_LENGTH = 50
export const MAX_ABOUT_ME_LENGTH = 1_000

export const MAX_EXPERIENCES_SIZE = 10
export const EXPERIENCE_POSITION_MAX_LENGTH = 50
export const EXPERIENCE_COMPANY_MAX_LENGTH = 50
export const EXPERIENCE_DURATION_MAX_LENGTH = 30
export const EXPERIENCE_DESCRIPTION_MAX_LENGTH = 1_000

export const MAX_EDUCATIONS_SIZE = 10
export const EDUCATION_DEGREE_MAX_LENGTH = 75
export const EDUCATION_UNIVERSITY_MAX_LENGTH = 75
export const EDUCATION_DURATION_MAX_LENGTH = 30

export const MAX_CONTACTS_SIZE = 10
export const CONTACT_TEXT_MAX_LENGTH = 50
export const CONTACT_HREF_MAX_LENGTH = 50

export const MAX_TECHNOLOGIES_LENGTH = 500

export const MAX_LANGUAGES_SIZE = 10
export const LANGUAGE_MAX_LENGTH = 25
export const VERSION_PREFIX = 'Version #'
