export const CV_VERSIONS_MAX_COUNT = 5
export const VERSION_PREFIX = 'Version #'

export const FULL_NAME_MAX_LENGTH = 50
export const POSITION_MAX_LENGTH = 50
export const ABOUT_ME_MAX_LENGTH = 1_000

export const EXPERIENCES_MAX_COUNT = 10
export const EXPERIENCE_POSITION_MAX_LENGTH = 50
export const EXPERIENCE_COMPANY_MAX_LENGTH = 50
export const EXPERIENCE_DURATION_MAX_LENGTH = 30
export const EXPERIENCE_DESCRIPTION_MAX_LENGTH = 1_000

export const EDUCATIONS_MAX_COUNT = 10
export const EDUCATION_DEGREE_MAX_LENGTH = 75
export const EDUCATION_UNIVERSITY_MAX_LENGTH = 75
export const EDUCATION_DURATION_MAX_LENGTH = 30

export const CONTACTS_MAX_COUNT = 10
export const CONTACT_TEXT_MAX_LENGTH = 50
export const CONTACT_HREF_MAX_LENGTH = 50

export const MAX_TECHNOLOGIES_LENGTH = 500

export const LANGUAGES_MAX_COUNT = 10
export const LANGUAGE_MAX_LENGTH = 25
