export const MAX_CV_VERSIONS = 5
export const MAX_FULL_NAME_LENGTH = 50
export const MAX_POSITION_LENGTH = 50
export const MAX_ABOUT_ME_LENGTH = 1_000
export const MAX_TECHNOLOGIES_LENGTH = 500
export const MAX_EXPERIENCES_SIZE = 10
export const MAX_EDUCATIONS_SIZE = 10
export const MAX_CONTACTS_SIZE = 10
export const MAX_LANGUAGES_SIZE = 10
export const VERSION_PREFIX = 'Version #'
