name: CI

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version:
          - 14.x
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - name: Install dependencies
        run: npm ci --no-progress
      - name: Lint
        run: npm run lint

  release-frontend:
    needs: lint
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version:
          - 14.x
    outputs:
      status: ${{ steps.result.outputs.status }}
    steps:
      - uses: actions/checkout@v3
      - name: Setup Git config
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "<>"
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - name: Install dependencies
        run: npm ci --no-progress
      - uses: actions-ecosystem/action-get-latest-tag@v1
        id: get-previous-tag
      - name: Release
        id: release
        run: npx ts-node ./scripts/release.ts --project=frontend
      - uses: actions-ecosystem/action-get-latest-tag@v1
        id: get-current-tag
      - name: Save status
        id: result
        run: |
          echo "Previous tag - ${{ steps.get-previous-tag.outputs.tag }}; Current tag - ${{ steps.get-previous-tag.outputs.tag }}"
          if [[ ${{ steps.get-previous-tag.outputs.tag }} != ${{ steps.get-previous-tag.outputs.tag }} ]]; then status='released'; else status='skipped'; fi
          echo ::set-output name=status::${status}
          echo Status - ${status}

  deploy-frontend:
    needs: release-frontend
    if: ${{ needs.release-frontend.outputs.status == 'released' }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version:
          - 14.x
    defaults:
      run:
        working-directory: ./projects/frontend
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - name: Install Firebase tools
        run: npm i -g firebase-tools
      - name: Install dependencies
        run: npm ci --no-progress
      - name: Build
        run: npm run build
        env:
          REACT_APP_API: ${{ secrets.API }}
          REACT_APP_FIREBASE_API_KEY: ${{ secrets.FIREBASE_API_KEY }}
          REACT_APP_FIREBASE_APP_ID: ${{ secrets.FIREBASE_APP_ID }}
          REACT_APP_FIREBASE_AUTH_DOMAIN: ${{ secrets.FIREBASE_AUTH_DOMAIN }}
          REACT_APP_FIREBASE_MESSAGING_SENDER_ID: ${{ secrets.FIREBASE_MESSAGING_SENDER_ID }}
          REACT_APP_FIREBASE_STORAGE_BUCKET: ${{ secrets.FIREBASE_STORAGE_BUCKET }}
          REACT_APP_FIREBASE_PROJECT_ID: ${{ secrets.FIREBASE_PROJECT_ID }}
          REACT_APP_SENTRY_DSN: ${{ secrets.SENTRY_DSN }}
      - name: Deploy
        run: firebase deploy --token ${{ secrets.FIREBASE_TOKEN }}

  release-backend:
    needs:
      - lint
      - release-frontend # run after this job to avoid git conflicts
    if: ${{ always() && needs.lint.result == 'success' }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version:
          - 14.x
    outputs:
      status: ${{ steps.result.outputs.status }}
    steps:
      - uses: actions/checkout@v3
      - name: Setup Git config
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "<>"
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - name: Install dependencies
        run: npm ci --no-progress
      - uses: actions-ecosystem/action-get-latest-tag@v1
        id: get-previous-tag
      - name: Release
        id: release
        run: npx ts-node ./scripts/release.ts --project=backend
      - uses: actions-ecosystem/action-get-latest-tag@v1
        id: get-current-tag
      - name: Save status
        id: result
        run: |
          echo "Previous tag - ${{ steps.get-previous-tag.outputs.tag }}; Current tag - ${{ steps.get-previous-tag.outputs.tag }}"
          if [[ ${{ steps.get-previous-tag.outputs.tag }} != ${{ steps.get-previous-tag.outputs.tag }} ]]; then status='released'; else status='skipped'; fi
          echo ::set-output name=status::${status}
          echo Status - ${status}

  deploy-backend:
    needs: release-backend
    if: ${{ needs.release-backend.outputs.status == 'released' }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version:
          - 14.x
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.12.12
        with:
          appdir: projects/backend
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: ${{secrets.HEROKU_APP_NAME}}
          heroku_email: ${{secrets.HEROKU_EMAIL}}
