name: Deploy backend to testing stage (Railway)

on: workflow_dispatch

jobs:
  deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version:
          - 16.x
    defaults:
      run:
        working-directory: ./packages/backend
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - name: Install Railway CLI
        run: npm i -g @railway/cli
      - name: Install dependencies
        run: npm ci --no-progress
      - name: Build
        run: npm run build
        env:
          PORT: ${{ secrets.PORT }}
          FRONTEND_ORIGIN: ${{ secrets.FRONTEND_ORIGIN }}
          FIREBASE_PROJECT_ID: ${{ secrets.FIREBASE_PROJECT_ID }}
          FIREBASE_PRIVATE_KEY: ${{ secrets.FIREBASE_PRIVATE_KEY }}
          FIREBASE_CLIENT_EMAIL: ${{ secrets.FIREBASE_CLIENT_EMAIL }}
          FIREBASE_DATABASE_URL: ${{ secrets.FIREBASE_DATABASE_URL }}
          FIREBASE_STORAGE_BUCKET: ${{ secrets.FIREBASE_STORAGE_BUCKET }}
          SENTRY_DSN: ${{ secrets.SENTRY_DSN }}
      - name: Deploy
        run: RAILWAY_TOKEN=${{ secrets.RAILWAY_TOKEN_TESTING }} railway up
